FROM java:8
MAINTAINER Josh Mandel

# Install required packages
RUN apt-get update
RUN apt-get install -y  --force-yes jekyll

RUN wget http://hl7-fhir.github.io/org.hl7.fhir.igpublisher.jar

RUN git clone --depth 1 https://github.com/hl7-fhir/fhir-svn/ fhir

RUN java -jar org.hl7.fhir.igpublisher.jar -ig fhir/tests/ig/test-ig.json
