#!/bin/bash

set -e

function finish {
  kill $KEEPALIVE_PID
}
trap finish EXIT

TARGET=$RANDOM

mkdir -p ~/uploading/$TARGET
cd ~/uploading/$TARGET

while true; do sleep 10; du -hs .; done &
KEEPALIVE_PID=$!
tar xzf - && date --iso-8601 > ~/uploading/$TARGET/done.txt

mv ~/uploading/www/fhir ~/uploading/fhir.$TARGET.old  || true

mkdir -p ~/uploading/www
mv ~/uploading/$TARGET/ ~/uploading/www/fhir
rm -rf ~/uploading/fhir.$TARGET.old || true

echo "fin"
