#!/bin/bash

set -e

TARGET=$RANDOM

mkdir -p ~/uploading/$TARGET
cd ~/uploading/$TARGET

while true; do sleep 10; du -hs .; done &
KEEPALIVE_PID=$!
tar xzf - && date --iso-8601 > ~/uploading/$TARGET/done.txt

mv ~/uploading/www/fhir ~/uploading/fhir.$TARGET.old
mv ~/uploading/$TARGET/ ~/uploading/fhir
rm -rf ~/uploading/fhir.$TARGET.old

echo "fin"
kill $KEEPALIVE_PID
