#!/bin/bash

set -e

TARGET=$RANDOM

mkdir -p ~/uploading/$TARGET
cd ~/uploading/$TARGET

while true; do sleep 10; du -hs .; done &
KEEPALIVE_PID=$!
tar xzf - && date --iso-8601 > ~/uploading/$TARGET/done.txt

mv ~/uploading/www ~/uploading/www.$TARGET.old
mv ~/uploading/$TARGET/ ~/uploading/www
rm -rf ~/uploading/www.$TARGET.old

echo "fin"
kill $KEEPALIVE_PID
