apiVersion: v1
data:
  ssh_authorized_key: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRh4advuDXquHexIHn44hY5E1oO8iay98ogCe4iLd/SDwsG7WzE77dnMsFpMmSAdQqbSmNLGKX87v3du0CzgQiGB5E+u4QxAqWBwfTRRyyLaBOryW5KDIwBmNkZPoI4sA5MT/sliNg0Cpaygw5n1oQA9Bk1ehdAIWLFEjXD0J+LUDQ0LEueF+eUwdJbPQjiLy2KogZ7+9rjRofx8G1MxxZGjikuiKd2s+sM/7Ikens84itpCG0/B9DO32QKRA5Cpculq5u3EU05Crwx/cXYevSMhQwJnz7isY/t9aIFy4XExIeqxL8FSXFvyTN8uRFxbxuq2DSbUZ9JzB0ixJxHiChmaQPpIQ8LkhUxJaBsEohb1S4BMKonNrHNuIoJwEpeoU/52A70glAEuQPsja2HjXQCiGVGoAmWrbWG7w8XsiAqjpxZl8QE67kMh97A41oUJSRyPaAT5QN/J1N7jkM0/7I88/uZZODkU6L2ybWOi08TVjJqFwlNvXIgM16Yem5rAOUE6jQD0EMa9U8CPaeFr2YtwKThT1IIkXRlsvjqNB3xBYf0JrDzJwIXzZVrHHwsETy1y/+3bmxpFYLo6QS4eZDsr3Htuz3k+fDbbvC+TA+JZ+x4X3b+2QB/QF4VacSom1aMf3eyCaewocrDvW+weOF/8idjo4UplCQfaj7Pqs7tQ==
  nginx.conf: |
    user  www-data;

    error_log  /var/log/nginx/error.log warn;
    pid        /run/nginx.pid;

    worker_processes  4;

    events {
        worker_connections  1024;
        multi_accept off;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        server_names_hash_bucket_size 64;

        client_max_body_size 64m;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log main buffer=16k;

        sendfile        on;
        tcp_nopush      on;
        tcp_nodelay     on;

        keepalive_timeout  65;
        keepalive_requests 100;

        #gzip  on;


        gzip on;
        gzip_http_version 1.1;
        gzip_vary on;
        gzip_comp_level 6;
        gzip_proxied any;
        gzip_types text/plain text/html text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript text/x-js;
        gzip_buffers 16 8k;
        gzip_disable "MSIE [1-6]\.(?!.*SV1)";
        map $http_accept $fhir_suffix {
            default   ".html";
            "application/fhir+json"  ".json";
            "application/fhir+xml"  ".xml";
            "application/json-ld"  ".jsonld";
            "text/turtle"  ".ttl";
            "text/shex"  ".shex";
        }


        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
    }
  sites-enabled.conf: |
    server {
        listen 80 default_server;

        server_name build.fhir.org;

        root /var/www/fhir;

        index index.html index.htm;

        expires 5m;
        include mime.types;
        types {
            application/fhir+json json;
            application/fhir+xml xml;
            application/json json;
            application/xml xml;
            text/plain log;
            text/plain md;
            application/json-ld jsonld;
            text/turtle ttl;
            text/shex shex;
        }
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
        add_header Vary Accept;

        try_files $uri $uri$fhir_suffix $uri/index.html   =404;
        location ~ ^/ig/(?<org>[^/]+)\/(?<repo>[^/]+)$ {
            rewrite [^/]$ $uri/ redirect;
        }
        location /ig {
            root /var/www;
            try_files $uri $uri$fhir_suffix $uri/index.html   =404;
        }
    }
kind: ConfigMap
metadata:
  name: ci-build-config
  namespace: fhir
