apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  name: buildk
  namespace: fhir
spec:
  activeDeadlineSeconds: 36000
  backoffLimit: 6
  completions: 1
  parallelism: 1
  suspend: false
  template:
    spec:
      containers:
      - name: ig-upload
        image: igbuild
        imagePullPolicy: Never
        command: ["/usr/local/bin/watch-and-publish"]
        args: []
        env:
        - name: ZULIP_EMAIL
          valueFrom:
            secretKeyRef:
              key: email
              name: zulip-secrets
        - name: ZULIP_API_KEY
          valueFrom:
            secretKeyRef:
              key: api_key
              name: zulip-secrets
        resources:
          requests:
            memory: 512Mi
        volumeMounts:
        - name: scratch
          mountPath: /scratch
        - mountPath: /etc/ci_build_keys
          name: keys
      - name: ig-build
        image: igbuild
        imagePullPolicy: Never
        env:
        - name: PUBLISHER_JAR_URL
          value: https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar
        - name: TX_SERVER_URL
          value: http://tx.fhir.org
        - name: DEADLINE_SECONDS
          value: "36000"
        - name: JAVA_MEMORY
          value: 19000m
        - name: IG_ORG
          value: "HL7"
        - name: IG_REPO
          value: "smart-app-launch"
        - name: IG_BRANCH
          value: "master"
        resources:
          limits:
            memory: 30Gi
          requests:
            memory: 1Gi
        volumeMounts:
        - name: scratch
          mountPath: /scratch
        - mountPath: /etc/ig.builder.keyfile.ini
          name: fhir-settings
          subPath: ig.builder.keyfile.ini
        - mountPath: /etc/fhir-settings.json
          name: fhir-settings
          subPath: fhir-settings.json
      restartPolicy: Never
      volumes:
      - name: scratch
        emptyDir: {}
      - name: keys
        secret:
          defaultMode: 256
          secretName: ci-build-keys
      - name: fhir-settings
        secret:
          defaultMode: 256
          secretName: fhir-settings
