#!/bin/bash

if [ ! -d "fhir/build" ]; then
  echo "" | git svn clone https://gforge.hl7.org/svn/fhir/trunk/build \
    -r 2403 \
    --username anonymous \
    --rewrite-root=http://gforge.hl7.org/svn/fhir/trunk/build \
    fhir/build
  pushd fhir/build
  git config push.default simple
  git remote add origin git@github.com:hl7-fhir/fhir-svn.git
  git fetch origin
  git branch -u origin/master
  popd
fi

while true; do
  sync;
  sleep 30;
done
