#!/bin/bash

set -e

function finish {
  kill $KEEPALIVE_PID
}
trap finish EXIT


IG_ORG=$1
IG_REPO=$2
DEPLOY_TO_BRANCH=${3:-master}
FAILURE_FLAG=${4:-success}

TARGET="$RANDOM_${IG_ORG}_${IG_REPO}"

mkdir -p ~/uploading/$TARGET
cd ~/uploading/$TARGET

while true; do sleep 5; du -hs .; done &
KEEPALIVE_PID=$!
tar xzf - && date --iso-8601 > ~/uploading/$TARGET/done.txt

if [ "$FAILURE_FLAG" == "failure" ]; then
    mkdir -p ~/uploading/www/ig/$IG_ORG/$IG_REPO/branches/$DEPLOY_TO_BRANCH
    rm -rf ~/uploading/www/ig/$IG_ORG/$IG_REPO/branches/$DEPLOY_TO_BRANCH/failure || true
    mv ~/uploading/$TARGET/ ~/uploading/www/ig/$IG_ORG/$IG_REPO/branches/$DEPLOY_TO_BRANCH/failure
else
    mv ~/uploading/www/ig/$IG_ORG/$IG_REPO/branches/$DEPLOY_TO_BRANCH ~/uploading/branch.$TARGET.old  || true
    mkdir -p ~/uploading/www/ig/$IG_ORG/$IG_REPO/branches/
    mv ~/uploading/$TARGET/ ~/uploading/www/ig/$IG_ORG/$IG_REPO/branches/$DEPLOY_TO_BRANCH
    rm -rf ~/uploading/branch.$TARGET.old || true
fi

set +e

cd ~/uploading/www/ig
find . -maxdepth 4 -mindepth 4  -type d -ctime +120  -exec rm -rf {} \;
find . -name build.log | sed 's|^./||'  | jq --raw-input . | jq -s . > builds.json

for f in `find . -mindepth 5  -maxdepth 5 -name qa.json`; do
    jq '. + {repo: input_filename[2:]}' $f;
done | jq --slurp  '.' > qas.json

echo "fin"
