#!/bin/bash

if [ ! -d "fhir/build" ]; then
  echo "" | git svn clone http://gforge.hl7.org/svn/fhir/trunk/build -r 2403 fhir/build --username anonymous
  pushd fhir/build
  ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  git remote add origin git@github.com:hl7-fhir/fhir-svn.git
  git fetch origin
  git branch -u origin/master
  popd
fi

while true; do
  sync;
  sleep 30;
done
