name: Build and Push Multi-Platform Docker Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        default: 'main'
        required: true
  push:
    branches:
      - main
    paths:
      - 'images/ig-publisher/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push multi-platform image for localdev
      run: |
        docker buildx build --push \
          --platform linux/amd64,linux/arm64 \
          --target localdev \
          -t ghcr.io/fhir/ig-publisher-localdev:latest \
          images/ig-publisher

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push multi-platform image for localdev
      run: |
        docker buildx build --push \
          --platform linux/amd64,linux/arm64 \
          --target localdev \
          -t hl7fhir/ig-publisher-base:latest \
          images/ig-publisher
